name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run typecheck
        run: yarn typecheck

      - name: Run checks
        run: yarn ci
